Parallel targets
nptscot/npt pull request #262
Opened 2023-08-18 21:24 UTC by mem48

First crack at #258

![image](https://github.com/nptscot/npt/assets/15819577/e7b11639-e911-4ef0-b0d9-a3364b655d91)

Untangling everything will take a while. But the main change, splitting the commute routing into separate targets is done.

This now means that when using `tar_make_future` code can be running while waiting for routing from cyclestreets. 

There is a bit more splitting to do. E.g. the schools and some of the task at the end.  E.g. doing the zone stats and the school stats in the same target results in unnecessary waiting. It should also be possible to build the final rnets before the balanced routing is done as the balanced routes are not on the website.

2023-08-19 07:34 UTC, Robinlovelace commented
Good to see. Will take a look now.

2023-08-19 07:37 UTC, mem48 commented
Schools now also split 

![image](https://github.com/nptscot/npt/assets/15819577/6db4b563-552e-446c-9b32-32060d0bde76)

2023-08-19 07:44 UTC, Robinlovelace commented
There are pros and cons:

- Pro: a bit faster. Do we know by how much? Best we can hope for is from ~24 hours to ~8 hours assuming best case 4x speed up.
- Con: code complexity. Rather than setting the network types in `parameters$plans` these are now hardcoded. There are a lot more lines of code.
- Con: harder to debug and understand.

So I'm not convinced. We can get some of the benefits by reviving #78 .

2023-08-19 07:46 UTC, Robinlovelace commented
Is there a way of doing this without adding so many extra lines of code?

2023-08-19 07:46 UTC, Robinlovelace commented
I wonder if this could be a good use case of static branching: https://books.ropensci.org/targets/static.html#map

2023-08-19 09:31 UTC, mem48 commented
It won't be 3x faster. The build can never be faster than the routing and the routing is 75% of the build time.

But it solves a scheduling problem. There are two computers involved in the build. The build computer and the cyclestreets server. Currently only one is working at any moment. This parallelisation allows both to work simultaneously.

There are slightly more lines of code in `_targets.R`  750 vs 566 but I find it much easier to read. Most targets now run a single function, and many are a single line long. 

You could easily compress

```
tar_target(rnet_gq_school_balanced, {
  segments2rnet(rs_school_balanced[[1]]$segments)
}),
```
to a single line if the number of lines of code matters. There is also some further cleaning that can be done.

I think this is easier to debug, as smaller targets mean it's clearer where a failure has occurred.

It also means smaller datasets `tar_load(uptake_commute_fastest)` is 1/4 the size of `tar_load(uptake_list_commute)`

2023-08-19 09:53 UTC, mem48 commented
In a way, this is the only further speed improvement that is worth doing. As the routing is the slowest process any time that the cyclestreets server is idle slows down the critical path and so the whole build. Splitting up the work like this ensures that cyclestreets has very little downtime. 

Once this is implemented there is no need to make any other stage faster as they will all be done while waiting for cyclestreets to finish the routing.

The last thing that needs doing is splitting the combining rnets work so that it does not require the balanced routes.  This will mean that the pmtiles can be built before all the routing is completed which would mean maximum possible performance.

2023-08-19 10:09 UTC, Robinlovelace commented
I see your points, although it does not move in the direction of automation. If we want to add/remove another plan type we have to manually comment out/remove/add lines of code, rather than just editing the config file.

Plan to approve after I see the results of this in any case.

Will test the latest version you have on a test with 250 and see what happens, and how much faster it is.

2023-08-19 10:22 UTC, Robinlovelace commented
Testing it out now...

2023-08-19 10:28 UTC, Robinlovelace commented
Current world view, is this really running on all cores @mem48 ?

![image](https://github.com/nptscot/npt/assets/1825120/05992fc2-cba0-468b-a795-5a182f740f42)

2023-08-19 10:30 UTC, Robinlovelace commented
Seems a bit quicker in sending the jobs: 

![image](https://github.com/nptscot/npt/assets/1825120/a5e9d331-af5d-4e4b-80de-63fb83c5184a)

2023-08-19 10:30 UTC, mem48 commented
No it only uses two workers

```
future::plan(future::multisession, workers = 2)
```

2023-08-19 10:31 UTC, Robinlovelace commented
How can we see if it's running in parallel from the output?

![image](https://github.com/nptscot/npt/assets/1825120/bc0ba7df-fb76-40d1-ba52-df61789f8f82)

2023-08-19 10:32 UTC, mem48 commented
You can see that it is building rnets before all the routing is done

2023-08-19 10:33 UTC, mem48 commented
A that it is building rnets in 0.2 seconds. I think that is targets way of saying "retrieving the finished work from the worker only took 0.2 seconds"

2023-08-19 10:40 UTC, Robinlovelace commented
Maybe I need to `tar_invalidate()`. Will try again...

2023-08-19 10:44 UTC, Robinlovelace commented
Just running 

```r
targets::tar_watch()
```

2023-08-19 10:48 UTC, Robinlovelace commented
Going to re-run starting with this:

![image](https://github.com/nptscot/npt/assets/1825120/e84527e9-1d44-4060-a664-cad69d7193ee)

2023-08-19 10:51 UTC, Robinlovelace commented
Currently stuck on 1st routing job it seems... 
![image](https://github.com/nptscot/npt/assets/1825120/9d9c2ece-7782-4c9a-8139-8981f6539aca)

2023-08-19 10:52 UTC, Robinlovelace commented
Will document how long it takes + and speed-up...

2023-08-19 12:04 UTC, Robinlovelace commented
Parallel version took just under 10 minutes

```
▶ end pipeline [9.815 minutes]
```

2023-08-19 12:22 UTC, Robinlovelace commented
Trying on the main branch..

2023-08-19 12:23 UTC, Robinlovelace commented
![image](https://github.com/nptscot/npt/assets/1825120/100d676b-5c85-419d-ad6f-7af86833d98e)

2023-08-19 13:09 UTC, Robinlovelace commented
Just under 11 minutes. So ~10% faster with 250 routes. Shall we try with a larger build? I think so.

```
▶ end pipeline [10.903 minutes]
```

2023-08-19 13:20 UTC, mem48 commented
Yes, the larger the build the bigger the difference but I wouldn't expect more than 20%.

2023-08-19 14:40 UTC, Robinlovelace commented
:+1: to separating them out but I don't see the link between this PR that parallelises the build and removing balanced routes which is a separate issue. On that note I've created #264 and an associated PR: #265 the changes to allow the build to pass should be smaller on that branch than this one.

2023-08-19 15:47 UTC, mem48 commented
I thought we agreed with sustrans that balanced routes should be part of the data just not in the website?

So we should still include the balanced routes and rnet, but not make them a prerequisite of making the combined rnet and pmtiles.

2023-08-19 17:24 UTC, Robinlovelace commented
Fine by me.

2023-09-07 09:44 UTC, Robinlovelace commented
Currently trying this on Windows:

![image](https://github.com/nptscot/npt/assets/1825120/bb83001e-0772-4354-9586-13da537b5f4a)

2023-09-07 10:22 UTC, Robinlovelace commented
Update and FYI @mem48 it's now done 2 sets of school routes and is at 50% memory use. I wonder if there's a way of removing all memory after a target has finished:


![image](https://github.com/nptscot/npt/assets/1825120/e4f1b231-d0f1-4a0f-8294-ddf99431433d)

2023-09-07 10:24 UTC, Robinlovelace commented
OK, I see garbage collection is on:

https://github.com/nptscot/npt/blob/46b47fb9238b279ce3c7ffd89453ae9837179e2d/_targets.R#L20

2023-09-07 10:25 UTC, Robinlovelace commented
Which would help explain why memory use has now dropped down again, to 18 GB.

2023-09-07 11:58 UTC, Robinlovelace commented
Heads-up @mem48 it failed with the following:

```
▶ start target rs_commute_fastest
✖ error target rs_commute_fastest
▶ end pipeline [1.665 hours]
Error:
! Error running targets::tar_make_future()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Timeout was reached: [api.cyclestreets.net] Operation timed out after 60008 milliseconds with 0 bytes received
```

2023-09-07 12:02 UTC, Robinlovelace commented
I think it's an R setting that auto time-outs after 1hr:

```r
options("timeout") 
# 60
```

2023-09-07 12:03 UTC, Robinlovelace commented
Going to update timeout. Current status.

![image](https://github.com/nptscot/npt/assets/1825120/37ebfd4e-0703-4f66-8c12-52ad1439eec4)

2023-09-07 12:48 UTC, Robinlovelace commented
Relevant issue: https://github.com/ropensci/rtweet/issues/229

2023-09-07 16:10 UTC, mem48 commented
I've pushed updated that splits out a lot of the late stage work related to zone stats

2023-09-07 16:11 UTC, mem48 commented
Your error does not seem to be related to the PR, but a problem with your connection to cyclestreets.

2023-09-07 16:14 UTC, mem48 commented
Could be connected to #261

2023-09-07 18:24 UTC, Robinlovelace commented
Progressing again now, I think... will check

2023-09-07 18:40 UTC, Robinlovelace commented
@mem48 it failed with the following:

```
✖ error target rs_commute_fastest
▶ end pipeline [3.451 hours]
Error:
! Error running targets::tar_make_future()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: no applicable method for 'group_by' applied to an object of class "NULL"
```

2023-09-07 19:06 UTC, mem48 commented
Have you cleared the old data files? `group_by` is in `get_routes` but I can't see why it would fail on a large batch and not a small batch.

2023-09-07 19:11 UTC, Robinlovelace commented
See #272

2023-09-08 10:04 UTC, mem48 commented
Updated `_targets.R` should reduce peak memory use by not loading two sets of routes into memory at the same time.

I made a chart to explain the workflow as the default layout is unclear.

![image](https://github.com/nptscot/npt/assets/15819577/59b3f95b-e593-4c03-9df2-a8f243a0bf09)

2023-09-08 10:58 UTC, Robinlovelace commented on _targets.R
> +  exists(rs_school_fastest) #Hack for scheduling
This will still load into memory the whole object. Worth opening an issue in the targets issue tracker IMO.

2023-09-08 10:58 UTC, Robinlovelace commented
> Updated `_targets.R` should reduce peak memory use by not loading two sets of routes into memory at the same time.
> 
> I made a chart to explain the workflow as the default layout is unclear.
> 
> ![image](https://user-images.githubusercontent.com/15819577/266575384-59b3f95b-e593-4c03-9df2-a8f243a0bf09.png)

Looks good.

2023-09-08 13:17 UTC, mem48 commented on _targets.R
> +  exists("rs_school_fastest") #Hack for scheduling
`exists()` only takes a character input i.e the name of the object, not the object itself. But if you quote the object name then targets does not recognise it for creating the dependency graph.  https://stackoverflow.com/questions/69662145/r-targets-package-how-to-refer-to-an-existing-target-using-a-string So I've gone back to using length.

Should still produce the desired result of lower peak memory use, but perhaps not a fast as I hoped.

2023-09-08 14:45 UTC, mem48 commented
National Build Running

![image](https://github.com/nptscot/npt/assets/15819577/19799a22-78f2-441c-80b2-df23035c9a3d)

using `tar_watch` before `tar_make_future` shows a cool real-time update. You can see that all the school's post-processing is done before the first batch of commute routing has been completed.

2023-09-08 14:46 UTC, mem48 commented
Currently with 4 workers and using a very manageable 3GB of RAM, but not working very hard at the moment because waiting for routes

2023-09-08 15:53 UTC, Robinlovelace commented
Good to hear and fingers crossed. FYI @mem48 I finally checked on my laptop and it did fail, with this message:

```
▶ end pipeline [4.591 hours]
Error:
! Error running targets::tar_make_future()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: cannot allocate vector of size 158.1 Mb
```

2023-09-08 17:24 UTC, mem48 commented
Peak memory post commuter routing is 81 GB
![image](https://github.com/nptscot/npt/assets/15819577/4486bb30-b19b-4080-b202-ab9accfa22d2)

Not that 79GB is on the single worker doing the routing. So this is not a parallel problem.

2023-09-08 18:47 UTC, Robinlovelace commented
The switch to pulling down both segment and route level geometries increased memory use.

2023-09-09 07:17 UTC, mem48 commented
Full build complete, high memory usage is due to large batch sizes now used in cyclestreets

2023-09-09 07:38 UTC, Robinlovelace commented
:tada:

2023-09-09 07:44 UTC, Robinlovelace reviewed
Looking good. See minor comments above. I'm going to reproduce the results with a small build to approving. Overall, great work Malcolm!

2023-09-09 07:44 UTC, Robinlovelace commented on R/zone_stats.R
> +make_commute_stats <- function(comm, nm){
Should be `=` to be consistent with the project's style.

2023-09-09 07:44 UTC, Robinlovelace commented on R/zone_stats.R
> -  comm_from <- tidyr::pivot_wider(comm_from,
Glad to see all this hardcoded and verbose code removed.

2023-09-09 07:44 UTC, Robinlovelace commented on R/zone_stats.R
> +  schl_to <- tidyr::pivot_wider(schl_to,
All this is a bit clunky. Any way to neaten it up?

2023-09-09 07:44 UTC, Robinlovelace commented on R/zone_stats.R
> +#' Function to summarise routes into zone statistics
Maybe move this to `code/tests` if not useful?

2023-09-09 07:44 UTC, Robinlovelace commented on _targets.R
> +# If your RAM limited use tar_make() to run one job at a time
:+1:

2023-09-09 07:44 UTC, Robinlovelace commented on _targets.R
> +library(magrittr) # Light load of %>%
We currently use 2 pipe operators. We should standardise on `|>`.

2023-09-09 07:45 UTC, Robinlovelace commented
Going to try with 250 routes...

2023-09-09 07:47 UTC, Robinlovelace commented
Also @mem48 can you share the pmtiles from the results? Will be good to check locally, I don't see them in the release.

2023-09-09 08:05 UTC, Robinlovelace commented
Another issue with the release @mem48: the secondary network seems way smaller than the primary network. Is this expected?

![image](https://github.com/nptscot/npt/assets/1825120/d7017802-6f11-4f64-b138-816fcbda5a53)

2023-09-09 08:12 UTC, Robinlovelace commented
A weird thing with the build pipeline, it seems that the save outputs target can complete before rnet and even some routing targets are complete:

![image](https://github.com/nptscot/npt/assets/1825120/837eee0c-a96b-458a-9d67-a18ed2e8a027)

Could that explain some of the small outputs?

2023-09-09 08:15 UTC, Robinlovelace commented
This can be seen in the dependency graph where the commute stats target for example happens 'after' the save targets target:

![image](https://github.com/nptscot/npt/assets/1825120/ec8794d3-d456-45fd-a415-351d9e2b511b)

2023-09-09 08:16 UTC, Robinlovelace commented
Other pathway of same image showing that save outputs does not depend on all the rnets being complete.

![image](https://github.com/nptscot/npt/assets/1825120/69c0956b-0558-4138-904c-28cf0f2e7ec3)

2023-09-09 08:17 UTC, mem48 commented
Need to replace `length(done_commute_balanced)` with `length(rnet_commute_balanced)`

2023-09-09 08:17 UTC, Robinlovelace requested changes
Some things not quite right with this, outputs in release have variable sizes for rnet files and save outputs target should always go after rnet targets.

2023-09-09 08:18 UTC, Robinlovelace commented
> Need to replace `length(done_commute_balanced)` with `length(rnet_commute_balanced)` in `upload_data`

OK, you happy to give it a bash? Good progress in any case.

2023-09-09 08:19 UTC, mem48 commented
Done

2023-09-09 08:19 UTC, Robinlovelace commented
OK, I'll try reproducing the results again.

2023-09-09 08:20 UTC, Robinlovelace commented
Did that affect the full build? Worth re-running your side also I think so we have complete outputs and pmtiles to check.

2023-09-09 08:23 UTC, Robinlovelace commented
Have you double checked 

```r
targets::tar_visnetwork(T)
```

After the change above @mem48 ?

2023-09-09 08:24 UTC, Robinlovelace commented
This is what I see after pulling down the latest changes. Not ready yet I think... Please double check and re-request review when good to go and I'll take a proper look and reproduce the results.

![image](https://github.com/nptscot/npt/assets/1825120/65d50c2b-135d-4097-a5af-13a6207268a6)

2023-09-09 08:31 UTC, mem48 commented
> This is what I see after pulling down the latest changes. Not ready yet I think... Please double check and re-request review when good to go and I'll take a proper look and reproduce the results.

THis looks fine to me, wht is the problem?

2023-09-09 08:33 UTC, Robinlovelace commented
> THis looks fine to me, wht is the problem?

`rnet_commute_balanced` generated after save outputs.

2023-09-09 08:33 UTC, mem48 commented
Save outputs does not use `rnet_commute_balanced`

2023-09-09 08:34 UTC, Robinlovelace commented
Aha, and the target could probably be commented out.

2023-09-09 08:34 UTC, Robinlovelace commented
Can you share the pmtiles resulting from the full build?

2023-09-09 08:38 UTC, mem48 commented
On the website already

2023-09-09 08:38 UTC, mem48 commented
I spotted one bug that the values are not rounded, now fixed in code

2023-09-09 08:40 UTC, Robinlovelace commented
> I spotted one bug that the values are not rounded, now fixed in code

Glad the review is helpful. Can you generate the pmtiles for comparison with previous build? Will check when ready, off to park.

2023-09-09 09:25 UTC, mem48 commented
Updated pmtiles now on server

2023-09-09 09:25 UTC, mem48 commented
![image](https://github.com/nptscot/npt/assets/15819577/a99460b0-e277-4eae-a563-73164c88cff1)

2023-09-09 12:27 UTC, Robinlovelace commented
Fantastic, will take a look at the test website now.

2023-09-09 12:31 UTC, Robinlovelace commented
Have updated the date here: https://github.com/nptscot/nptscot.github.io/commit/477cb6cb7c78bdad78f399d2a69fe3c9bc4dfa73

2023-09-09 12:38 UTC, Robinlovelace approved these changes

2023-09-09 12:38 UTC, merged

2023-09-09 12:47 UTC, Robinlovelace commented
Merged! Also trying a build here for reproducibility's sake, let's see what happens..

2023-09-09 19:27 UTC, Robinlovelace commented
Chugging away fine with 1 worker on laptop with 64 GB RAM FYI @mem48, the various tweaks, particularly the `routes_done` hack, seem to have worked.