306 build error
nptscot/npt pull request #309
Opened 2023-10-25 12:06 UTC by joeytalbot

A couple of attempts at using 'if' or 'case_when' statements

2023-10-25 21:17 UTC, Robinlovelace requested changes
Few comments, then this should be good to go. Did you manage to get it working?

2023-10-25 21:17 UTC, Robinlovelace commented on _targets.R
> +  }, TRUE ~ simd)
```suggestion
  if ("ï..Data_Zone" %in% names(simd)) {
    simd = simd %>%
      rename(Data_Zone = `ï..Data_Zone`)    
  }

2023-10-25 21:17 UTC, Robinlovelace commented on _targets.R
> +  # if(length(simd$`ï..Data_Zone`)>1) {
I think this comment should be tidied up.

2023-10-25 21:17 UTC, Robinlovelace commented on _targets.R
> +  # if(length(simd$`ï..Data_Zone`)>1) {
Is this supposed to be there?

2023-10-25 21:17 UTC, Robinlovelace commented on code/tests/import_SMID.R
> +simd = case_when(length(simd$`ï..Data_Zone`)>1 ~ {
Same as above: simple `if` statement is easier to read I think.

2023-10-26 11:09 UTC, juanfonsecaLS1 commented
you could try specifying the `encoding` parameter in the `read.csv` calls, if you don't want to change the function. 

[See this](https://stackoverflow.com/questions/14363085/invalid-multibyte-string-in-read-csv)

2023-10-26 11:47 UTC, Robinlovelace commented
Fixed in #310

2023-10-26 11:47 UTC, closed without merging