Add utility zone stats
nptscot/npt pull request #356
Opened 2023-12-11 22:29 UTC by mem48

Zone stats for utility trips

2023-12-11 22:32 UTC, Robinlovelace requested changes
Looks good, minor tweak to code style for consistency requested.

2023-12-11 22:32 UTC, Robinlovelace commented on R/zone_stats.R
> +  comm_to <- dplyr::group_by(comm, endDZ, purpose)
Consistent assignment operator please.

2023-12-12 12:42 UTC, Robinlovelace reviewed
Let me give it a spin to ensure it works. Will approve + merge ASAP to keep the momentum up.

2023-12-12 12:42 UTC, Robinlovelace commented on _targets.R
> +                             names_glue = "{schooltype}_{.value}",
Nice syntax.

2023-12-12 12:44 UTC, Robinlovelace commented
Heads-up @mem48 I'm planning to push to this branch, let me know if you're making any other additional changes.

2023-12-12 12:59 UTC, Robinlovelace commented
@mem48 I get this error:

```
▶ start target save_outputs
✖ error target save_outputs
▶ end pipeline [1.764 minutes]
Warning messages:
1: Thats a lot of columns for the GeoJSON, are they all needed? 
2: Thats a lot of columns for the GeoJSON, are they all needed? 
3: Thats a lot of columns for the GeoJSON, are they all needed? 
4: Thats a lot of columns for the GeoJSON, are they all needed? 
5: Thats a lot of columns for the GeoJSON, are they all needed? 
6: running command 'cd outputdata; tippecanoe -o data_zones.pmtiles --name=data_zones --layer=data_zones --attribution=UniverstyofLeeds --minimum-zoom=6 -zg --coalesce-smallest-as-needed --detect-shared-borders --extend-zooms-if-still-dropping --maximum-tile-bytes=5000000 --simplification=10 --buffer=5 --force  data_zones.geojson' had status 110 
7: running command 'cd outputdata; tippecanoe -o dasymetric_verylow.pmtiles --name=dasymetric --layer=dasymetric --attribution=OS --minimum-zoom=4 --maximum-zoom=6 --coalesce-smallest-as-needed --detect-shared-borders --maximum-tile-bytes=5000000 --simplification=1 --buffer=5 --force dasymetric_verylow.geojson; tippecanoe -o dasymetric_low.pmtiles --name=dasymetric --layer=dasymetric --attribution=OS --minimum-zoom=7 --maximum-zoom=9 --coalesce-smallest-as-needed --detect-shared-borders --maximum-tile-bytes=5000000 --simplification=1 --buffer=5 --force dasymetric_low.geojson; tippecanoe -o dasymetric_med.pmtiles --name=dasymetric --layer=dasymetric --attribution=OS --minimum-zoom=10 --maximum-zoom=14 --coalesce-smallest-as-needed --detect-shared-borders --maximum-tile-bytes=5000000 --simplification=2 --buffer=5 --force dasymetric_med.geojson; tippecanoe -o dasymetric_high.pmtiles --name=dasymetric --layer=dasymetric --attribution=OS -zg --minimum-zoom=15 --extend-zooms-if-still-dropping - [... truncated] 
8: 4 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
Error:
! Error running targets::tar_make_future()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Some files do not exist
```

2023-12-12 13:00 UTC, Robinlovelace commented
From the terminal:

```
cd outputdata; tippecanoe -o data_zones.pmtiles --name=data_zones --layer=data_zones --attribution=UniverstyofLeeds --minimum-zoom=6 -zg --coalesce-smallest-as-needed --detect-shared-borders --extend-zooms-if-still-dropping --maximum-tile-bytes=5000000 --simplification=10 --buffer=5 --force  data_zones.geojson
data_zones.geojson: No such file or directory
0 features, 4 bytes of geometry, 0 bytes of string pool
Did not read any valid geometries
```

2023-12-12 13:33 UTC, atumscott approved these changes

2023-12-12 13:33 UTC, Robinlovelace approved these changes

2023-12-12 13:33 UTC, merged