add coherent funtion into targets
nptscot/npt pull request #411
Opened 2024-02-15 11:12 UTC by wangzhao0217

- add dplyr::bind_rows
- add coherent into targets

2024-02-15 11:51 UTC, Robinlovelace reviewed
Looks promising. There are a lot of moving parts and may make sense to merge #410 first, no rush on this and great start. Can you share a visualisation of the outputs of this code @wangzhao0217 ?

2024-03-04 11:30 UTC, Robinlovelace approved these changes

2024-03-04 11:30 UTC, Robinlovelace commented on _targets.R
> +    devtools::load_all()
I think you can remove this. When testing locally use 

```r
tar_source()
``

2024-03-04 13:29 UTC, Robinlovelace requested changes
This error needs to be fixed:

```
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: object 'all_city_coherent_networks_75' not found
```

2024-03-04 13:32 UTC, wangzhao0217 commented
> This error needs to be fixed:
> 
> ```
> Error:
> ! Error running targets::tar_make()
>   Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
>   Debugging guide: https://books.ropensci.org/targets/debugging.html
>   How to ask for help: https://books.ropensci.org/targets/help.html
>   Last error: object 'all_city_coherent_networks_75' not found
> ```

Hi Robin, pls pull, this is not the latest

2024-03-04 13:34 UTC, Robinlovelace commented
OK my bad. Will try with latest version.

2024-03-04 13:35 UTC, Robinlovelace commented
Also don't have this file:

```
data-raw/combined_network_tile.geojson
```

2024-03-04 15:12 UTC, Robinlovelace reviewed
Heads-up @wangzhao0217 I'm still hitting an error:

```
▶ start target pmtiles_school
✔ skip target zones_contextual
✖ error target pmtiles_coherent
▶ end pipeline [5.12 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: object 'all_city_coherent_networks' not found
```

2024-03-04 15:16 UTC, Robinlovelace commented
I think

```
    for (city in names(all_city_coherent_networks)) {
``` 

Should be replaced with

```
    for (city in parameters$coherent_area) {
```

2024-03-04 15:18 UTC, Robinlovelace commented
This would also work: 

```
    for (city in names(coherent_network)) {
```

Note @wangzhao0217 the name of the target is the only thing that targets can 'see', not the name of objects within each object.

2024-03-04 21:16 UTC, Robinlovelace commented
Looking good @wangzhao0217 only issue now is this:

```
✖ error target coherent_network
▶ end pipeline [3.081 hours]
Warning message:
15 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Cannot open "inputdata/sg_intermediatezone_bdry_2011.gpkg"; The file doesn't seem to exist.
```

Maybe add the data as a release in inputdata if not already in there (I couldn't find it).

2024-03-05 12:04 UTC, wangzhao0217 commented
> Looking good @wangzhao0217 only issue now is this:
> 
> ```
> ✖ error target coherent_network
> ▶ end pipeline [3.081 hours]
> Warning message:
> 15 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
> Error:
> ! Error running targets::tar_make()
>   Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
>   Debugging guide: https://books.ropensci.org/targets/debugging.html
>   How to ask for help: https://books.ropensci.org/targets/help.html
>   Last error: Cannot open "inputdata/sg_intermediatezone_bdry_2011.gpkg"; The file doesn't seem to exist.
> ```
> 
> Maybe add the data as a release in inputdata if not already in there (I couldn't find it).

Hi Robin, here is the release of all inputdata for CN: https://github.com/nptscot/npt/releases/tag/Coherent-inputdata

2024-03-05 12:33 UTC, wangzhao0217 commented
Hi Robin
There are 3 files required for coherent network:
  sg_intermediatezone_bdry_2011 = sf::st_read("inputdata/sg_intermediatezone_bdry_2011.gpkg")
  las_scotland_2023 = sf::st_read("inputdata/las_scotland_2023.geojson")
can be downloaded from https://github.com/nptscot/npt/releases/tag/boundaries-2024

  MasterMap = sf::st_read("inputdata/MasterMap_Scotland.geojson")
I have shared this file with you on Team

2024-03-05 13:31 UTC, Robinlovelace commented
Now hitting this error after running `tar_make()`:

```
▶ start target rs_commute_balanced
✖ error target coherent_network
▶ end pipeline [17.876 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: the condition has length > 1
```

2024-03-05 13:32 UTC, Robinlovelace commented
OK just did 

```bash
git pull
```

now trying again.

2024-03-05 18:45 UTC, robinlovelace-ate approved these changes

2024-03-05 18:46 UTC, Robinlovelace approved these changes

2024-03-05 18:46 UTC, merged

2024-03-05 19:20 UTC, Robinlovelace commented
https://github.com/nptscot/npt/assets/1825120/57311972-2dc6-4433-bc51-2df3ac66b318