osm os
nptscot/npt pull request #538
Opened 2024-09-24 10:02 UTC by wangzhao0217

- **Create osm_vs_os**
- **add comapre between osm and os**
- **Add files via upload**
- **cn aggregation and geometries**
- **remove coherent build outside of build.R, the code/corenet_build_OSM.R is left as unfinished**

2024-09-24 12:58 UTC, wangzhao0217 commented on osm_os/osm_cohesive_network_complex.geojson
yes, agree Robin!

2024-09-25 10:42 UTC, wangzhao0217 commented on R/get_orcp_cn.R
> +cohesive_network_city_boundary = sf::st_transform(cohesive_network_city_boundary, crs = 27700)
I've checked the code and removed the relevant lines. The CRS was made consistent in the previous steps.

2024-09-25 10:42 UTC, wangzhao0217 commented on R/get_orcp_cn.R
> +        # tryCatch({
Removed

2024-09-25 12:47 UTC, Robinlovelace approved these changes

2024-09-26 13:26 UTC, Robinlovelace reviewed
:fire:

2024-09-30 13:36 UTC, Robinlovelace reviewed
Looks good to me.

2024-10-04 21:25 UTC, Robinlovelace approved these changes
Looks good, I'm convinced this is working, happy for this to be merged when you are @wangzhao0217

2024-10-07 03:01 UTC, Robinlovelace requested changes
Minor tweaks requested, let's get this merged.

2024-10-07 03:01 UTC, Robinlovelace commented on .devcontainer/postCreateCommand.sh
> +sudo ln -s /root/.cargo/bin/rustc /usr/local/bin/rustc
Not needed if we switch to the `ghcr.io/geocompx/docker:rust` image, right?

2024-10-07 10:49 UTC, Robinlovelace approved these changes

2024-10-07 10:49 UTC, Robinlovelace commented on .devcontainer/devcontainer.json
> +	"postCreateCommand": "bash ./.devcontainer/postCreateCommand.sh"
Good fix!

2024-10-07 10:53 UTC, Robinlovelace approved these changes

2024-10-07 10:53 UTC, Robinlovelace commented on .devcontainer/postCreateCommand.sh
> -sudo ln -s ~/.cargo/bin/odjitter /usr/local/bin/odjitter
We need these!

2024-10-07 10:53 UTC, merged